-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 17:45:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS Tahir_SchoolDB;
CREATE DATABASE IF NOT EXISTS Tahir_SchoolDB;
USE Tahir_SchoolDB;
-- -----------------------------------------------------
-- Table `Parking_Lot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parking_Lot` ;

CREATE TABLE IF NOT EXISTS `Parking_Lot` (
  `lot_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `spaces_available` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`lot_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `student_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NULL,
  `last_name` VARCHAR(30) NULL,
  `date_of_birth` DATE NULL,
  `date_of_enroll` DATE NULL,
  `password` VARCHAR(55) NULL,
  `parking_lot_id` TINYINT UNSIGNED NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `FK_STUDENT_LOT_LOTID_idx` (`parking_lot_id` ASC) VISIBLE,
  CONSTRAINT `FK_STUDENT_LOT_LOTID`
    FOREIGN KEY (`parking_lot_id`)
    REFERENCES `Parking_Lot` (`lot_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `dept_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teacher` ;

CREATE TABLE IF NOT EXISTS `Teacher` (
  `teacher_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NULL,
  `last_name` VARCHAR(30) NULL,
  `date_of_hiring` DATE NULL,
  `password` VARCHAR(55) NULL,
  `dept_id` SMALLINT UNSIGNED NULL,
  `parking_lot_id` TINYINT UNSIGNED NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`teacher_id`),
  INDEX `FK_TEACHER_TEACHERID_DEPTID_idx` (`dept_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `FK_TEACHER_LOT_LOTID_idx` (`parking_lot_id` ASC) VISIBLE,
  CONSTRAINT `FK_TEACHER_DEPT_DEPTID`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Department` (`dept_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TEACHER_LOT_LOTID`
    FOREIGN KEY (`parking_lot_id`)
    REFERENCES `Parking_Lot` (`lot_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff` ;

CREATE TABLE IF NOT EXISTS `Staff` (
  `staff_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NULL,
  `last_name` VARCHAR(30) NULL,
  `date_of_hiring` DATE NULL,
  `dept_id` SMALLINT UNSIGNED NULL,
  `parking_lot_id` TINYINT UNSIGNED NULL,
  `password` VARCHAR(55) NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `FK_STAFF_STAFFID_DEPTID_idx` (`dept_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `FK_STAFF_LOT_LOTID_idx` (`parking_lot_id` ASC) VISIBLE,
  CONSTRAINT `FK_STAFF_DEPT_DEPTID`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Department` (`dept_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STAFF_LOT_LOTID`
    FOREIGN KEY (`parking_lot_id`)
    REFERENCES `Parking_Lot` (`lot_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teacher_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teacher_Role` ;

CREATE TABLE IF NOT EXISTS `Teacher_Role` (
  `teacher_role_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `payscale` DECIMAL(10,2) NULL,
  PRIMARY KEY (`teacher_role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teacher-Teacher_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teacher-Teacher_Role` ;

CREATE TABLE IF NOT EXISTS `Teacher-Teacher_Role` (
  `ttr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teacher_id` INT UNSIGNED NOT NULL,
  `teacher_role_id` SMALLINT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`ttr_id`),
  INDEX `FK_TTR_TEACHER_TEACHERID_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `FK_TTR_TEACHERROLE_TEACHERROLEID_idx` (`teacher_role_id` ASC) VISIBLE,
  CONSTRAINT `FK_TTR_TEACHER_TEACHERID`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `Teacher` (`teacher_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TTR_TEACHERROLE_TEACHERROLEID`
    FOREIGN KEY (`teacher_role_id`)
    REFERENCES `Teacher_Role` (`teacher_role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff_Role` ;

CREATE TABLE IF NOT EXISTS `Staff_Role` (
  `staff_role_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `payscale` DECIMAL(10,2) NULL,
  PRIMARY KEY (`staff_role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff-Staff_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff-Staff_Role` ;

CREATE TABLE IF NOT EXISTS `Staff-Staff_Role` (
  `ssr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `staff_id` INT UNSIGNED NOT NULL,
  `staff_role_id` SMALLINT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`ssr_id`),
  INDEX `FK_SSR_STAFF_STAFFID_idx` (`staff_id` ASC) VISIBLE,
  INDEX `FK_SSR_STAFFROLE_STAFFROLEID_idx` (`staff_role_id` ASC) VISIBLE,
  CONSTRAINT `FK_SSR_STAFF_STAFFID`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SSR_STAFFROLE_STAFFROLEID`
    FOREIGN KEY (`staff_role_id`)
    REFERENCES `Staff_Role` (`staff_role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Major` ;

CREATE TABLE IF NOT EXISTS `Major` (
  `major_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`major_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student-Major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student-Major` ;

CREATE TABLE IF NOT EXISTS `Student-Major` (
  `student_major_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_id` INT UNSIGNED NOT NULL,
  `major_id` SMALLINT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`student_major_id`),
  INDEX `FK_STUMAJ_STUDENT_STUDENTID_idx` (`student_id` ASC) VISIBLE,
  INDEX `FK_STUMAJ_MAJOR_MAJORID_idx` (`major_id` ASC) VISIBLE,
  CONSTRAINT `FK_STUMAJ_STUDENT_STUDENTID`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STUMAJ_MAJOR_MAJORID`
    FOREIGN KEY (`major_id`)
    REFERENCES `Major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subject` ;

CREATE TABLE IF NOT EXISTS `Subject` (
  `subject_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `dept_id` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `FK_SUBJECT_DEPT_DEPTID_idx` (`dept_id` ASC) VISIBLE,
  CONSTRAINT `FK_SUBJECT_DEPT_DEPTID`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Department` (`dept_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class` ;

CREATE TABLE IF NOT EXISTS `Class` (
  `class_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `credit_hours` DECIMAL(3,1) NULL,
  `cost` DECIMAL(7,2) NULL,
  `teacher_salary` DECIMAL(10,2) NULL,
  `subject_id` SMALLINT UNSIGNED NULL,
  `number` VARCHAR(6) NULL,
  PRIMARY KEY (`class_id`),
  INDEX `FK_CLASS_SUBJECT_SUBJECTID_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `FK_CLASS_SUBJECT_SUBJECTID`
    FOREIGN KEY (`subject_id`)
    REFERENCES `Subject` (`subject_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Major_Requirement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Major_Requirement` ;

CREATE TABLE IF NOT EXISTS `Major_Requirement` (
  `major_req_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `major_id` SMALLINT UNSIGNED NOT NULL,
  `class_id` SMALLINT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`major_req_id`),
  INDEX `FK_MAJORREQ_MAJOR_MAJORID_idx` (`major_id` ASC) VISIBLE,
  INDEX `FK_MAJORREQ_CLASS_CLASSID_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `FK_MAJORREQ_MAJOR_MAJORID`
    FOREIGN KEY (`major_id`)
    REFERENCES `Major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MAJORREQ_CLASS_CLASSID`
    FOREIGN KEY (`class_id`)
    REFERENCES `Class` (`class_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Semester` ;

CREATE TABLE IF NOT EXISTS `Semester` (
  `semester_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `year` SMALLINT UNSIGNED NULL,
  `season` VARCHAR(20) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`semester_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroom` ;

CREATE TABLE IF NOT EXISTS `Classroom` (
  `classroom_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `building_name` VARCHAR(45) NULL,
  `room_number` VARCHAR(45) NULL,
  `seats` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`classroom_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class_Section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class_Section` ;

CREATE TABLE IF NOT EXISTS `Class_Section` (
  `class_section_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `days` VARCHAR(10) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `class_id` SMALLINT UNSIGNED NULL,
  `classroom_id` SMALLINT UNSIGNED NULL,
  `semester_id` SMALLINT UNSIGNED NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`class_section_id`),
  INDEX `FK_CLASSSECTION_CLASS_CLASSID_idx` (`class_id` ASC) VISIBLE,
  INDEX `FK_CLASSECTION_SEMESTER_SEMESTERID_idx` (`semester_id` ASC) VISIBLE,
  INDEX `FK_CLASSECTION_CLASSROOM_CLASSROOMID_idx` (`classroom_id` ASC) VISIBLE,
  CONSTRAINT `FK_CLASSSECTION_CLASS_CLASSID`
    FOREIGN KEY (`class_id`)
    REFERENCES `Class` (`class_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CLASSECTION_SEMESTER_SEMESTERID`
    FOREIGN KEY (`semester_id`)
    REFERENCES `Semester` (`semester_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CLASSECTION_CLASSROOM_CLASSROOMID`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `Classroom` (`classroom_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class_Section-Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class_Section-Student` ;

CREATE TABLE IF NOT EXISTS `Class_Section-Student` (
  `css_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_id` INT UNSIGNED NOT NULL,
  `class_section_id` INT UNSIGNED NOT NULL,
  `grade` VARCHAR(2) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`css_id`),
  INDEX `FK_CSS_STUDENT_STUDENTID_idx` (`student_id` ASC) VISIBLE,
  INDEX `FK_CSS_CLASSECTION_CLASSSECTIONID_idx` (`class_section_id` ASC) VISIBLE,
  CONSTRAINT `FK_CSS_STUDENT_STUDENTID`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CSS_CLASSECTION_CLASSSECTIONID`
    FOREIGN KEY (`class_section_id`)
    REFERENCES `Class_Section` (`class_section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class_Section-Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class_Section-Teacher` ;

CREATE TABLE IF NOT EXISTS `Class_Section-Teacher` (
  `cst_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teacher_id` INT UNSIGNED NOT NULL,
  `class_section_id` INT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`cst_id`),
  INDEX `FK_CST_TEACHER_TEACHERID_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `FK_CST_CLASSECTION_CLASSECTIONID_idx` (`class_section_id` ASC) VISIBLE,
  CONSTRAINT `FK_CST_TEACHER_TEACHERID`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `Teacher` (`teacher_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CST_CLASSECTION_CLASSECTIONID`
    FOREIGN KEY (`class_section_id`)
    REFERENCES `Class_Section` (`class_section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Module` ;

CREATE TABLE IF NOT EXISTS `Module` (
  `module_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `class_section_id` INT UNSIGNED NULL,
  PRIMARY KEY (`module_id`),
  INDEX `FK_MODULE_CLASSECTION_CLASSSECTIONID_idx` (`class_section_id` ASC) VISIBLE,
  CONSTRAINT `FK_MODULE_CLASSECTION_CLASSSECTIONID`
    FOREIGN KEY (`class_section_id`)
    REFERENCES `Class_Section` (`class_section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Document` ;

CREATE TABLE IF NOT EXISTS `Document` (
  `document_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `link` VARCHAR(255) NULL,
  `module_id` INT UNSIGNED NULL,
  PRIMARY KEY (`document_id`),
  INDEX `FK_DOCUMENT_MODULE_MODULEID_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `FK_DOCUMENT_MODULE_MODULEID`
    FOREIGN KEY (`module_id`)
    REFERENCES `Module` (`module_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Assignment` ;

CREATE TABLE IF NOT EXISTS `Assignment` (
  `assignment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `link` VARCHAR(255) NULL,
  `top_score` TINYINT UNSIGNED NULL,
  `module_id` INT UNSIGNED NULL,
  PRIMARY KEY (`assignment_id`),
  INDEX `FK_ASSN_MODULE_MODULEID_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `FK_ASSN_MODULE_MODULEID`
    FOREIGN KEY (`module_id`)
    REFERENCES `Module` (`module_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student-Completed-Assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student-Completed-Assignment` ;

CREATE TABLE IF NOT EXISTS `Student-Completed-Assignment` (
  `sca_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_id` INT UNSIGNED NOT NULL,
  `assignment_id` INT UNSIGNED NOT NULL,
  `submittal_link` VARCHAR(255) NULL,
  `score` TINYINT UNSIGNED NULL,
  `answer_text` TEXT NULL,
  PRIMARY KEY (`sca_id`),
  INDEX `FK_SCA_STUDENT_STUDENTID_idx` (`student_id` ASC) VISIBLE,
  INDEX `FK_SCA_ASSN_ASSIGNMENTID_idx` (`assignment_id` ASC) VISIBLE,
  CONSTRAINT `FK_SCA_STUDENT_STUDENTID`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SCA_ASSN_ASSIGNMENTID`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `Assignment` (`assignment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Quiz` ;

CREATE TABLE IF NOT EXISTS `Quiz` (
  `quiz_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `max_score` TINYINT UNSIGNED NULL,
  `module_id` INT UNSIGNED NULL,
  PRIMARY KEY (`quiz_id`),
  INDEX `FK_QUIZ_MODULE_MODULEID_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `FK_QUIZ_MODULE_MODULEID`
    FOREIGN KEY (`module_id`)
    REFERENCES `Module` (`module_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz_Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Quiz_Question` ;

CREATE TABLE IF NOT EXISTS `Quiz_Question` (
  `quiz_question_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` TEXT NULL,
  `quiz_id` INT UNSIGNED NULL,
  PRIMARY KEY (`quiz_question_id`),
  INDEX `FK_QUIZQUEST_QUIZ_QUIZID_idx` (`quiz_id` ASC) VISIBLE,
  CONSTRAINT `FK_QUIZQUEST_QUIZ_QUIZID`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `Quiz` (`quiz_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz_Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Quiz_Answer` ;

CREATE TABLE IF NOT EXISTS `Quiz_Answer` (
  `quiz_answer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(255) NULL,
  `is_correct` TINYINT NULL,
  `quiz_question_id` INT UNSIGNED NULL,
  PRIMARY KEY (`quiz_answer_id`),
  INDEX `FK_QUIZANS_QUIZQUEST_QUIZQUESTID_idx` (`quiz_question_id` ASC) VISIBLE,
  CONSTRAINT `FK_QUIZANS_QUIZQUEST_QUIZQUESTID`
    FOREIGN KEY (`quiz_question_id`)
    REFERENCES `Quiz_Question` (`quiz_question_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student-Quiz_Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student-Quiz_Answer` ;

CREATE TABLE IF NOT EXISTS `Student-Quiz_Answer` (
  `sqa_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_id` INT UNSIGNED NOT NULL,
  `quiz_answer_id` INT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`sqa_id`),
  INDEX `FK_SQA_STUDENT_STUDENTID_idx` (`student_id` ASC) VISIBLE,
  INDEX `FK_SQA_QUIZANS_QUIZANSID_idx` (`quiz_answer_id` ASC) VISIBLE,
  CONSTRAINT `FK_SQA_STUDENT_STUDENTID`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SQA_QUIZANS_QUIZANSID`
    FOREIGN KEY (`quiz_answer_id`)
    REFERENCES `Quiz_Answer` (`quiz_answer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Required_Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Required_Resource` ;

CREATE TABLE IF NOT EXISTS `Required_Resource` (
  `req_resource_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `class_section_id` INT UNSIGNED NULL,
  PRIMARY KEY (`req_resource_id`),
  INDEX `FK_CLASSRESOURCE_CLASSECTION_CLASSECTIONID_idx` (`class_section_id` ASC) VISIBLE,
  CONSTRAINT `FK_REQRESOURCE_CLASSECTION_CLASSECTIONID`
    FOREIGN KEY (`class_section_id`)
    REFERENCES `Class_Section` (`class_section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroom_Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroom_Resource` ;

CREATE TABLE IF NOT EXISTS `Classroom_Resource` (
  `classroom_resource_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `quantity` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`classroom_resource_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroom-Classroom_Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroom-Classroom_Resource` ;

CREATE TABLE IF NOT EXISTS `Classroom-Classroom_Resource` (
  `ccr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `classroom_id` SMALLINT UNSIGNED NOT NULL,
  `classroom_resource_id` SMALLINT UNSIGNED NOT NULL,
  `quantity_assigned` SMALLINT NULL,
  PRIMARY KEY (`ccr_id`),
  INDEX `FK_CCR_CLASSROOM_CLASSROOMID_idx` (`classroom_id` ASC) VISIBLE,
  INDEX `FK_CCR_CLASSROOMRESOURCE_CLASSROOMRESOURCEID_idx` (`classroom_resource_id` ASC) VISIBLE,
  CONSTRAINT `FK_CCR_CLASSROOM_CLASSROOMID`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `Classroom` (`classroom_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CCR_CLASSROOMRESOURCE_CLASSROOMRESOURCEID`
    FOREIGN KEY (`classroom_resource_id`)
    REFERENCES `Classroom_Resource` (`classroom_resource_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student_Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student_Payment` ;

CREATE TABLE IF NOT EXISTS `Student_Payment` (
  `student_payment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_id` INT UNSIGNED NOT NULL,
  `payment_amount` DECIMAL(10,2) NULL,
  `date_made` DATE NULL,
  `semester_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`student_payment_id`),
  INDEX `FK_STUDENTPAYMENT_STUDENT_STUDENTID_idx` (`student_id` ASC) VISIBLE,
  INDEX `FK_STUDENTPAYMENT_SEMESTER_SEMESTERID_idx` (`semester_id` ASC) VISIBLE,
  CONSTRAINT `FK_STUDENTPAYMENT_STUDENT_STUDENTID`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STUDENTPAYMENT_SEMESTER_SEMESTERID`
    FOREIGN KEY (`semester_id`)
    REFERENCES `Semester` (`semester_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teacher_Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teacher_Payment` ;

CREATE TABLE IF NOT EXISTS `Teacher_Payment` (
  `teacher_payment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teacher_id` INT UNSIGNED NOT NULL,
  `payment_amount` DECIMAL(10,2) NULL,
  `date_made` DATE NULL,
  PRIMARY KEY (`teacher_payment_id`),
  INDEX `FK_TCHPAYMT_TEACHER_TEACHERID_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `FK_TCHPAYMT_TEACHER_TEACHERID`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `Teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff_Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff_Payment` ;

CREATE TABLE IF NOT EXISTS `Staff_Payment` (
  `staff_payment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `staff_id` INT UNSIGNED NOT NULL,
  `payment_amount` DECIMAL(10,2) NULL,
  `date_made` DATE NULL,
  PRIMARY KEY (`staff_payment_id`),
  INDEX `FK_STAFFPAYMT_STAFF_STAFFID_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `FK_STAFFPAYMT_STAFF_STAFFID`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Organization` ;

CREATE TABLE IF NOT EXISTS `Organization` (
  `org_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `classroom_id` SMALLINT UNSIGNED NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `days` VARCHAR(45) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  PRIMARY KEY (`org_id`),
  INDEX `FK_ORG_CLASSROOM_CLASSROOMID_idx` (`classroom_id` ASC) VISIBLE,
  CONSTRAINT `FK_ORG_CLASSROOM_CLASSROOMID`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `Classroom` (`classroom_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Org-Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Org-Student` ;

CREATE TABLE IF NOT EXISTS `Org-Student` (
  `org_student_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_id` INT UNSIGNED NOT NULL,
  `org_id` SMALLINT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`org_student_id`),
  INDEX `FK_ORGSTUDENT_STUDENT_STUDENTID_idx` (`student_id` ASC) VISIBLE,
  INDEX `FK_ORGSTUDENT_ORG_ORGID_idx` (`org_id` ASC) VISIBLE,
  CONSTRAINT `FK_ORGSTUDENT_STUDENT_STUDENTID`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ORGSTUDENT_ORG_ORGID`
    FOREIGN KEY (`org_id`)
    REFERENCES `Organization` (`org_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Org-Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Org-Teacher` ;

CREATE TABLE IF NOT EXISTS `Org-Teacher` (
  `org_teacher_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teacher_id` INT UNSIGNED NOT NULL,
  `org_id` SMALLINT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`org_teacher_id`),
  INDEX `FK_ORGTEACHER_TEACHER_TEACHERID_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `FK_ORGTEACHER_ORG_ORGID_idx` (`org_id` ASC) VISIBLE,
  CONSTRAINT `FK_ORGTEACHER_TEACHER_TEACHERID`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `Teacher` (`teacher_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ORGTEACHER_ORG_ORGID`
    FOREIGN KEY (`org_id`)
    REFERENCES `Organization` (`org_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `admin_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(55) NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Email` ;

CREATE TABLE IF NOT EXISTS `Email` (
  `email_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(65) NULL,
  `student_id` INT UNSIGNED NULL,
  `teacher_id` INT UNSIGNED NULL,
  `staff_id` INT UNSIGNED NULL,
  PRIMARY KEY (`email_id`),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE,
  INDEX `FK_EMAIL_STUDENT_STUDENTID_idx` (`student_id` ASC) VISIBLE,
  INDEX `FK_EMAIL_TEACHER_TEACHERID_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `FK_EMAIL_STAFF_STAFFID_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `FK_EMAIL_STUDENT_STUDENTID`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EMAIL_TEACHER_TEACHERID`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `Teacher` (`teacher_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EMAIL_STAFF_STAFFID`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
